### ISSUE TITLE
Inductor Error: aten.native_layer_norm_backward.default  Illegal Memory Access

### ISSUE THREAD

**Issue by eellison** [pytorch/torchdynamo#926]
`python /scratch/eellison/work/torchdynamo/benchmarks/microbenchmarks/operatorbench.py --op=aten.native_layer_norm_backward.default --dtype=float32 --suite=huggingface`

>Running aten.native_layer_norm_backward.default
Iter 0
Iter 1
Iter 2
Iter 3
Iter 4
Iter 5
Iter 6
Iter 7
Iter 8
Iter 9
Iter 10
error aten.native_layer_norm_backward.default
CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Iter 11```

Same error happens with `native_layer_norm.default`

> CUDA_VISIBLE_DEVICES=6 python /scratch/eellison/work/torchdynamo/benchmarks/microbenchmarks/operatorbench.py --op=aten.native_layer_norm.default --dtype=float32 --suite=huggingface

**Comment by ngimel** [comment]
It's a caching issue (likely simpy expr caching issue), when I start directly from iter 9, the launch parameters are generated correctly, and no IMA, I suspect there's a similar caching issue in #1178, as it runs correctly when attempting to minify, when only a single graph object is compiled.

**Comment by ngimel** [comment]
Both this and #1178 are fixed by disabling `_simplify_loops` caching https://github.com/pytorch/torchdynamo/blob/138eb96c36c6ba5a14e65d28fad3cbd5a6e6dcfc/torchinductor/codegen/common.py#L29 because it accesses `V.graph.sizevar.replacements` internally, thus cache based on inputs only is invalid. 
Should we roll manual cache here that also checks `replacements`? cc @jansel
